name: 'Deploy Topology'
description: 'Deploys topology resources'

inputs:
  env:
    description: “dev qa uat staging prod”
    required: true
  az_sub_id:
    description: “Azure subscription id”
    required: true
  az_rg_topology_n:
    description: “Azure resourceGroup name”
    required: true

runs:
  using: 'composite'
  steps:
    # Deploy Bicep file
  - name: deploy
    uses: azure/arm-deploy@v1
    with:
      scope: resourcegroup
      subscriptionId: ${{ inputs.az_sub_id }}
      resourceGroupName: ${{ inputs.az_rg_topology_n }}
      deploymentMode: Complete
      template: ./topology.bicep
      parameters: env=${{ inputs.env }}
      failOnStdErr: false