on: [push]
name: Deploy Azure Resource
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@v2

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure Resource
    - uses: ./.github/actions/deploy-az-resource
      with:
        env: "dev"
        az_rg_topology_n: "rg-bicephub-dev-eastus2"